# Generated by Django 3.1.4 on 2020-12-27 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoronaVirus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='', max_length=50)),
                ('total_cases', models.CharField(default='', max_length=50)),
                ('new_cases', models.CharField(default='', max_length=50)),
                ('total_deaths', models.CharField(default='', max_length=50)),
                ('new_deaths', models.CharField(default='', max_length=50)),
                ('total_recovered', models.CharField(default='', max_length=50)),
                ('active_cases', models.CharField(default='', max_length=50)),
                ('total_tests', models.CharField(default='', max_length=50)),
                ('population', models.CharField(default='', max_length=50)),
                ('continent', models.CharField(default='', max_length=50)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'coronavirus',
                'verbose_name_plural': 'coronavirus',
            },
        ),
    ]
