# Generated by Django 3.1.4 on 2020-12-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coronavirus',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
