# Generated by Django 3.1.4 on 2020-12-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201229_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coronavirus',
            name='active_cases',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='coronavirus',
            name='continent',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='coronavirus',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='coronavirus',
            name='new_cases',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='coronavirus',
            name='new_deaths',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='coronavirus',
            name='population',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='coronavirus',
            name='total_cases',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='coronavirus',
            name='total_deaths',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='coronavirus',
            name='total_recovered',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='coronavirus',
            name='total_tests',
            field=models.CharField(max_length=50),
        ),
    ]
