# Generated by Django 3.1.4 on 2020-12-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201229_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coronavirus',
            name='total_cases',
            field=models.CharField(max_length=50),
        ),
    ]
